//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TransportManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ticket
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ticket()
        {
            this.Cancels = new HashSet<Cancel>();
        }
    
        public int TicketId { get; set; }
        public Nullable<int> CityId { get; set; }
        public string TicketNo { get; set; }
        public string Bus_Name { get; set; }
        public string Time { get; set; }
        public string Taka { get; set; }
        public Nullable<int> PassengerId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cancel> Cancels { get; set; }
        public virtual User User { get; set; }
    }
}
